### ISSUE TITLE
Compiles but no longer outputs anything.

### ISSUE THREAD

**Issue by majortom64** [MatsMoll/HTMLKit-code-converter#2]
I recently tried to use this, and it complies successfully, but now longer seems to generate any out put. Any plans to update this to Vapor 4? Any other plans?

**Comment by mattesmohr** [comment]
@majortom64 I have implement the converter in HTMLKit. It comes with the next release. You can close the issue.

**Comment by mattesmohr** [comment]
@majortom64 I have implemented the converter into HTMLKit. It comes with the next release. You can close the issue if you want and if its okay for @MatsMoll.
